#+ name: Population history of Brussels
#+ description: Population figures over time for the City of Brussels, using statement qualifiers (point in time). Try the chart plugin.
PREFIX wd:       <http://www.wikidata.org/entity/>
PREFIX wdt:      <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd:       <http://www.bigdata.com/rdf#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p:        <http://www.wikidata.org/prop/>
PREFIX ps:       <http://www.wikidata.org/prop/statement/>
PREFIX pq:       <http://www.wikidata.org/prop/qualifier/>

SELECT ?year ?population WHERE {
  wd:Q239 p:P1082 ?statement .
  ?statement ps:P1082 ?population ;
             pq:P585 ?date .
  BIND(YEAR(?date) AS ?year)
}
ORDER BY ?year
