#+ name: Map: UNESCO World Heritage in the Benelux
#+ description: World Heritage Sites in Belgium, the Netherlands and Luxembourg on a map.
PREFIX wd:       <http://www.wikidata.org/entity/>
PREFIX wdt:      <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd:       <http://www.bigdata.com/rdf#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?site ?siteLabel ?countryLabel ?coordinates WHERE {
  VALUES ?country { wd:Q31 wd:Q55 wd:Q32 }
  ?site wdt:P1435 wd:Q9259 ;
        wdt:P17 ?country ;
        wdt:P625 ?coordinates .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,fr,de,nl". }
}
