#+ name: Vocabularies by tag
#+ description: How many vocabularies are registered per LOV tag (domain)?
PREFIX voaf: <http://purl.org/vocommons/voaf#>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?tag (COUNT(?vocabulary) AS ?vocabularies) WHERE {
  ?vocabulary a voaf:Vocabulary ;
              dcat:keyword ?tag .
}
GROUP BY ?tag
ORDER BY DESC(?vocabularies)
