#+ name: Abstract of a resource in several languages
#+ description: The DBpedia abstract of 'Semantic Web' in English, French, German and Dutch.
PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX dbr:  <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?language ?abstract WHERE {
  dbr:Semantic_Web dbo:abstract ?abstract .
  BIND(LANG(?abstract) AS ?language)
  FILTER(?language IN ("en", "fr", "de", "nl"))
}
