#+ name: Operational points in Belgium
#+ description: Name, unique OP id (UOPID) and type of all operational points in Belgium.
PREFIX era:  <http://data.europa.eu/949/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX country: <http://publications.europa.eu/resource/authority/country/>

SELECT ?op ?name ?uopid ?typeLabel WHERE {
  ?op a era:OperationalPoint ;
      era:inCountry country:BEL ;
      era:opName ?name .
  OPTIONAL { ?op era:uopid ?uopid }
  OPTIONAL {
    ?op era:opType ?type .
    ?type skos:prefLabel ?typeLabel .
    FILTER(LANGMATCHES(LANG(?typeLabel), "en"))
  }
}
ORDER BY ?name
