#+ name: Licences
#+ description: The licence authority table used to describe the licence of datasets and distributions.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?licence ?label WHERE {
  GRAPH <http://publications.europa.eu/resource/authority/licence> {
    ?licence a skos:Concept ;
          skos:prefLabel ?label .
    FILTER(LANG(?label) = "en")
  }
}
