#+ name: Currencies
#+ description: The currency authority table.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc:   <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?concept ?code ?label WHERE {
  ?concept skos:inScheme <http://publications.europa.eu/resource/authority/currency> ;
           skos:prefLabel ?label .
  FILTER(LANG(?label) = "en")
  OPTIONAL { ?concept dc:identifier ?code }
}
ORDER BY ?code
