#+ name: File types
#+ description: The file-type authority table used for dct:format in DCAT-AP metadata.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc:   <http://purl.org/dc/elements/1.1/>

SELECT ?concept ?code ?label WHERE {
  ?concept skos:inScheme <http://publications.europa.eu/resource/authority/file-type> ;
           skos:prefLabel ?label .
  FILTER(LANG(?label) = "en")
  OPTIONAL { ?concept dc:identifier ?code }
}
ORDER BY ?code
