#+ name: List all authority tables
#+ description: The EU Vocabularies authority tables (countries, languages, corporate bodies, file types, ...) are SKOS concept schemes. Lists all of them with their English name.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?scheme ?label WHERE {
  ?scheme a skos:ConceptScheme .
  FILTER(STRSTARTS(STR(?scheme), "http://publications.europa.eu/resource/authority/"))
  OPTIONAL { ?scheme skos:prefLabel ?label . FILTER(LANG(?label) = "en") }
}
ORDER BY ?scheme
