#+ name: Search AGROVOC concepts
#+ description: AGROVOC concepts whose English label contains 'wheat', using SKOS-XL labels.
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>

SELECT ?concept ?label WHERE {
  ?concept a skos:Concept ;
           skosxl:prefLabel/skosxl:literalForm ?label .
  FILTER(LANG(?label) = "en" && CONTAINS(LCASE(STR(?label)), "wheat"))
}
ORDER BY ?label
LIMIT 100
