#+ name: Map: sections of line in Switzerland
#+ description: Line geometries of Swiss sections of line, drawn as linestrings by the Geo plugin.
PREFIX era:  <http://data.europa.eu/949/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:  <http://www.opengis.net/ont/geosparql#>
PREFIX country: <http://publications.europa.eu/resource/authority/country/>

SELECT ?sol ?length ?wkt WHERE {
  ?sol a era:SectionOfLine ;
       era:inCountry country:CHE ;
       geo:hasGeometry/geo:asWKT ?wkt .
  OPTIONAL { ?sol era:lengthOfSectionOfLine ?length }
}
